return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.config',
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    ensure_installed = {
      'bash',
      'diff',
      'html',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'vim',
      'vimdoc',
      'python',
      'javascript',
      'typescript',
      'tsx',
      'go',
      'gomod',
      'gosum',
      'json',
      'yaml',
      'dockerfile',
    },
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = { enable = true, disable = { 'yaml' } },
  },
}
